enabled: true
name: dogecoin

daemon:
  host: 127.0.0.1
  port: 9333
  user: testuser
  password: testpass

wallet:
  address: nib2LgCtNghgojBiz6Ynu8jWaWHjLFiL47

rewards:
  myxWybbhUkGzGF7yaf2QVNx3hh3HWTya5t: 1

stratum:
  bind: 0.0.0.0
  port: 3333
  diff: 16
  vardiff:
    enabled: true
    minDiff: 8
    maxDiff: 512
    targetTime: 15
    retargetTime: 90
    variancePercent: 30
